ALTER TABLE policy
ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE policy
ALTER COLUMN id RESTART WITH 3;

ALTER TABLE expenses
ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE expenses
ALTER COLUMN id RESTART WITH 6;